### ISSUE TITLE
Times not shown for stops with times

### ISSUE THREAD

**Issue by thomastrillium** [brendannee/gtfs-to-html#25]
I working with the GTFS at data.trilliumtransit.com/gtfs/beloittransit-wi-us/beloittransit-wi-us-test.zip

See timetables and config.json below.

Notes

- `timetable_stop_order.txt` is present but incomplete. I'm guessing this is not a problem but if timetable_stop_order needs to include references to all timetables, that could be my problem.
- the config.json has `"showOnlyTimepoint": true,` and for the timetables in `timetable_stop_order.txt`, only the timepoints are in the file (I also tested including non-timepoints for those timetables in the file, but that forced them to be shown)
- only 12272016 forward timetables are included in zip
- these trips are exported as a group from our system, so I'm moderately confident that all the empty timepoints have times (and I've manually checked a few)

any ideas? cc @nomeq

[beloit1.zip](https://github.com/brendannee/gtfs-to-html/files/608180/beloit1.zip)

**Comment by trilliumtransit** [comment]
Checking the new timetables, I found a lot of code that simply got converted to strings in the html, e.g. `<col class="run_#{idx} #{(trip.trip_short_name) ? 'trip_short_name_' + trip.trip_short_name : ''}" id="trip_id_#{trip.trip_id}">`, but uncertain what is wrong.

I ran the gtfs through an old version of gtfs-to-html, and the timetables turned out fine. I have not progressively run commits to figure out at which point it breaks, but I had a local directory with commit 801a13a55519b2ca24cc88a21b7f158be7159e69 still running and it produced accurate timetables (attached).
[beloit2.zip](https://github.com/brendannee/gtfs-to-html/files/617765/beloit2.zip)

**Comment by brendannee** [comment]
I just published version 0.5.0 which should solve most or all of these issues.

Try generating it with this latest version and let me know if you have any issues.
